###########################################################
#      MAINTAINER: Mahmoud Zalt <mahmoud@zalt.me>         #
###########################################################

# PHP + NGINX Container #----------------------------------
php-nginx:
  image: chuanty/phpnginx:2.0
  container_name: php-nginx
  ports:
    - "80:80"
    - "9001:9001"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ../:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
    - redis
    - elasticsearch
  environment:
    - REDIS_PORT=6379
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200

# MySQL Container #----------------------------------------
mysql:
  image: mysql:5.6
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: homestead
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret

# Redis Container #----------------------------------------
redis:
  image: chuanty/redis:3.0
  container_name: redis
  ports:
    - "6379:6379"
  volumes_from:
    - data
  volumes:
    - ./logs/redis:/var/log/redis
  restart: always

# Elasticsearch Container #--------------------------------
elasticsearch:
  image: chuanty/elasticsearch:5.1.2
  container_name: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - cluster.name=shaka_es-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
  mem_limit: 1g
  volumes:
    - ./data/es:/usr/share/elasticsearch/data

# Data Volume Container #----------------------------------
data:
  build: data
  container_name: data
  volumes:
    - /var/lib/mysql
    - /var/lib/redis

